name: generate-ascii-multijob.yml
on:
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsy Program
        run: sudo apt-get install cowsay -y

      - name: Executing Cowsy AMD
        run: cowsay -f dragon "Run for cover , Im a Dragon...RAWR" >> dragon.txt

      - name: Sleep for 30 secs
        run: sleep 30

  test_job_2:
    runs-on: ubuntu-latest
    steps:

      - name: Sleep for 10 secs
        run: sleep 10

      - name: Test File Exists
        run: grep -i "unicorn" dragon.txt

  deploy_job_3:
    runs-on: ubuntu-latest
    steps:

      - name: Read File
        run: cat dragon.txt

      - name: Deploy
        run: echo Deploying...
      